package com;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
  public String getGreeting() {
    return "Akhilesh Hello";
  }

  public static void main(String[] args) {
    System.out.println(new App().getGreeting());
  }
}
